### ISSUE TITLE
Output generated file to stdout

### ISSUE THREAD

**Issue by pacak** [msrd0/cargo-doc2readme#117]
In *nix land specifying - as a file name usually means stdin for input and stdout for output. When I used `-o -` it created a file called `-` which is a bit odd.

Also can you consider disabling clap's colors in help by default? [relevant docs](https://docs.rs/clap/latest/clap/builder/struct.App.html#method.disable_colored_help). Color scheme they use by default makes it harder to read than no color at all but I'd like to keep colors in the remaining output so setting NO_COLOR env var is not a solution.

**Comment by msrd0** [comment]
I agree, `-` should be stdout. PRs welcome.

Regarding the colored help output, I don't think that it makes it harder to read. This is what it looks like in my terminal (alacritty):

![Screenshot_2022-08-08-14-31-26](https://user-images.githubusercontent.com/7853372/183418541-78e304e1-4e3a-4782-822e-82199ed66e4a.png)

You can of course always use `|cat` to remove colors, i.e. `cargo doc2readme -h |cat` will display the help message without colors.

**Comment by pacak** [comment]
> This is what it looks like in my terminal (alacritty):

Bright spots are distracting and my eye keeps slipping...

> You can of course always use |cat to remove colors, i.e. cargo doc2readme -h |cat will display the help message without colors.

There's several ways to do this but ideally it shouldn't be necessary in the first place.

**Comment by msrd0** [comment]
> There's several ways to do this but ideally it shouldn't be necessary in the first place.

Well, removing colors is much easier than adding them, so I think I'll keep 'em on by default.

**Comment by msrd0** [comment]
Just FYI, I just updated clap to 4.0 and the colors seems to be gone now: #201

**Comment by pacak** [comment]
Yes, `clap` is less bright now and default formatting is more compact.
