### ISSUE TITLE
output formatting - spaces before end of the line

### ISSUE THREAD

**Issue by pacak** [msrd0/cargo-doc2readme#121]
Generated markdown contains spaces between the last character and the end of the line. While it should not affect how this markdown is rendered this makes even `git diff` to highlight them... Would be great to trim those.

**Comment by msrd0** [comment]
Can you give me an example when this occurs? I looked through a few of my readmes, but found none with any trailing spaces.

**Comment by pacak** [comment]
This

```rust
//! # Design goals: restrictions
//!
//! The main restriction library sets is that parsed values (but not the fact that parser succeeded
//! or failed) can't be used to decide how to parse subsequent values. In other words parsers don't
//! have the monadic strength, only the applicative one.
//!
//! To give an example, following description is allowed:
//!
//! > Program takes one of `--stdout` or `--file` flag to specify the output target, when it is `--file`
//! > program also requires `-f` attribute with the file name
//!
//! But this one is not allowed:
//!
//! > Program takes an `-o` attribute with possible values of `'stdout'` and `'file'`, when it's `'file'`
//! > program also requires `-f` attribute with the file name
//!
//! This set of restrictions allows to extract information about the structure of the computations
//! to generate help and overall results in less confusing enduser experience
```

generates this

```
> Program takes one of `--stdout` or `--file` flag to specify the output target, when it is `--file` program also requires `-f` attribute with the file name
> 
> 
But this one is not allowed:


> Program takes an `-o` attribute with possible values of `'stdout'` and `'file'`, when it’s `'file'` program also requires `-f` attribute with the file name
> 
> 
```

I haven't published the whole thing yet

**Comment by msrd0** [comment]
Oh I see, it's not spaces at the end of a line containing content, but rather it keeping indent on empty lines. I did a lot of testing with different markdown editors to ensure that all of them recognize my output, and excessive empty lines with previous indentation fixed something. I don't recall what it was, but I also don't feel like debugging this just because indents on empty lines are for some reason discouraged. `git diff` being "less pretty" is definitely acceptable.

**Comment by pacak** [comment]
I see. I'll check the remaining examples and if they are the same - will
close the ticket. Sorry for the noise.
