### ISSUE TITLE
Feature Request: Use ascending numbers for enumerated lists

### ISSUE THREAD

**Issue by niluxv** [msrd0/cargo-doc2readme#137]
Example doc in `lib.rs`:
```rust
//! Several items:
//! 1. Item one
//! 2. Item two
```

Output in README:
```md
Several items:

 1. Item one
 1. Item two
```

(Expected output:
```md
Several items:

 1. Item one
 2. Item two
```
)

**Comment by msrd0** [comment]
No that's fine. The numbers don't matter, your markdown viewer should automatically put the correct numbers in.

**Comment by niluxv** [comment]
Ok, I see readability is a non goal
> easy readability of the generated markdown source code

But it is still suboptimal, since otherwise the generated markdown files are in fact quite readable.

**Comment by msrd0** [comment]
I see ... if this is a rather small change that does not increase code complexity and is unlikely to require a bunch of maintainance along the way, I'll merge a PR if you want to create one.

**Comment by msrd0** [comment]
> easy readability of the generated markdown source code

I mainly put that in so that people don't ask me to preserve their nicely formatted and aligned markdown tables.

**Comment by niluxv** [comment]
Looks like a small change. I'll create a PR this sometime this week.

**Comment by niluxv** [comment]
Hm, solving my particular issue probably isn't hard, but with nested lists the behaviour right now *is* wrong:

In:
```rust
//! Several items:
//! 1. Item one
//! 2. Item two
//!     1. Subitem one
//!     2. Subitem two
```

Out:
```md
Several items:

 1. Item one
 1. Item two 1. Subitem one
	 1. Subitem two
```

I'm not sure how easy fixing that is.

**Comment by msrd0** [comment]
Oh yeah that's a separate bug

**Comment by msrd0** [comment]
This is actually super easy to implement. I forgot we need to keep track of the numbers anyways since the first one matters.
