### ISSUE TITLE
[Feature] Feature Flags

### ISSUE THREAD

**Issue by LuckyTurtleDev** [msrd0/cargo-doc2readme#189]
Currently no option exists to enable feature flags in doc2readme. This means doc2readme can to create links for functions, which are not available with the default features.

For example in https://github.com/LuckyTurtleDev/more-wallpapers/pull/7#pullrequestreview-1192074089 the link for `set_random_wallpapers_from_vec()` cannot be created. Instead, doc2readme create a link to a non existing `set_random_wallpapers_from_vec()` file.

**Comment by msrd0** [comment]
This should either be done in a way where `--features` is only accepted if `--expand-macros` is also set, or at least generates a warning if `--features` are set but `--expand-macros` is not used. Especially, the user shouldn't assume that feature flags (or any cfg for this matter) is honored unless `--expand-macros` is being used.
