### ISSUE TITLE
[Bug]  linker `cc` not found at nightly image

### ISSUE THREAD

**Issue by LuckyTurtleDev** [msrd0/cargo-doc2readme#190]
It looks like the cc linker is missing at the current nightly docker image.

For example this ci fail https://github.com/LuckyTurtleDev/more-wallpapers/actions/runs/3534612074/jobs/5931687750.
It does not have a custom linker defended.
```
INFO  [cargo_doc2readme::input] Running rustc -Zunpretty=expanded
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.1
   Compiling syn v1.0.96
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn` due to previous error
Error: Failed to read crate code: Cargo failed to expand the macros

**Comment by msrd0** [comment]
Interesting. Does the musl toolchain from rustup finally support dynamic linking and procedural macros? Last time I checked it was completely impossible to use dynamic linking with rustup's musl toolchain
