### ISSUE TITLE
--check flag

### ISSUE THREAD

**Issue by niluxv** [msrd0/cargo-doc2readme#33]
I use `cargo doc2readme` to generate my readmes for crates, and would be interested in checking the readme to be up to date in CI. For this, it would be useful if `cargo doc2readme` offered a `--check` flag similar to e.g. `cargo fmt --check`.

**Comment by msrd0** [comment]
Duplicate of #19. Feel free to share implementation ideas if you have any.

**Comment by niluxv** [comment]
I'm sorry. Hadn't seen that issue.
