### ISSUE TITLE
Handle #![doc = macro_call!(...)]

### ISSUE THREAD

**Issue by scrabsha** [msrd0/cargo-doc2readme#37]
This could be a nice-to-have, as it would allow to generate documentation with macros. For instance [`dep-doc`] users to get their readme correctly generated!

A solution would be to run `cargo +nightly rustc -- -Z unpretty=expanded`, which outputs the whole crate in stdout, with the macros expanded. Then we can pass that to `syn` and do the regular process.

Another option would be to use the Rustc nightly API. This option is more difficult from my experience.

[`dep-doc`]: https://github.com/scrabsha/dep-doc/

**Comment by msrd0** [comment]
This sounds like a nice idea. We could add a command-line flag to pre-process the readme by running it through nightly rustc first. PRs welcom.

**Comment by scrabsha** [comment]
Can you assign this issue to me so that i can start working on it?

**Comment by msrd0** [comment]
@scrabsha Done :)

**Comment by pacak** [comment]
It is still kind of broken. 

Code I have contains this:

```rust
//! docs
#![doc = include_str!("../doc.md")]
//! more docs
```

First I run it as is and getting this error message:

```
% cargo doc2readme
     Reading /path/src/lib.rs                                                                                                                                                                                        
thread 'main' panicked at 'Unable to read file: expected literal', src/main.rs:194:71                                                                                                                                                         
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After digging into sources and checking though issues I find this ticket and trying to run it with `--expand-macros` as specified in https://github.com/msrd0/cargo-doc2readme/pull/38 and getting this:

```
% cargo  doc2readme  --expand-macros
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
thread 'main' panicked at 'Failed to read crate code: Cargo failed to expand the macros', src/main.rs:159:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Crate I'm working on contains both a library and a binary. some hacking on `cargo-doc2readme` (hardcoding `--lib`) I'm getting this in resulting file which looks is not something I would expect:

```
docs
[doc = include_str!(“../doc.md”)][__link1]
more docs
```

**Comment by msrd0** [comment]
The later error message looks like a bug that happens when you have a library and binary target. Please open a new issue.

I however don't fully understand the output you are seeing - can you share the relevant part of `cargo expand`? The `[doc = ` part should be eaten fully by rustc/syn and not processed by this crate at all.

**Comment by pacak** [comment]
I don't really understand the output either. `cargo expand` contains no traces of `include_str`. I'm not sure where `cargo-doc2readme` gets it from.

**Comment by pacak** [comment]
I should be able to provide a better report with a way to reproduce it in a couple of days if you are interested, for now I'm trying to get the documentation working so I can publish the crate.
