### ISSUE TITLE
🔍 Docs.rs Search Links Not Searching

### ISSUE THREAD

**Issue by zicklag** [msrd0/cargo-doc2readme#5]
Whenever a dependency ends up being "*" in the docs.rs link, it causes docs.rs to redirect to the latest actual version, but that redirect doesn't preserve the search query string unfortunately. :/ Not sure what the best thing to do about it is.

I wish there was an easier way to generate docs.rs links, especially because it would be really nice to be able to link straight to the item instead of using search. I wonder if we could make an API call to docs.rs to get the search index, use the search to find the exact URL to the item, and then use that URL for the link. Just an idea.

**Comment by zicklag** [comment]
Here's the where the search index is: https://docs.rs/raui/0.35.0/search-index-20210511-1.54.0-nightly-5c0292654.js

We might be able to parse that.

**Comment by msrd0** [comment]
I know, that's why I'm trying to use cargo to find a version of instead of using `*`. How did you end up with a dependency without a version?

**Comment by zicklag** [comment]
I just tried running the project on the [`raui`](https://github.com/RAUI-labs/raui) crate. It already uses `cargo readme` for it's readme so I just added the `{{links}}` section to the readme template and ran `cargo doc2readme` instead of `cargo readme`.

**Comment by msrd0** [comment]
ok so the problem seems to be that dependencies with a `path` don't get their version extracted.

**Comment by msrd0** [comment]
I just published 0.0.3 which should create working links for your crate

**Comment by zicklag** [comment]
Awesome, thanks!
