### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by msrd0** [msrd0/cargo-doc2readme#53]
There is no good error handling and reporting functionality in this crate. This was reported several times, including by @pacak in #37:

```
% cargo doc2readme
     Reading /path/src/lib.rs                                                                                                                                                                                        
thread 'main' panicked at 'Unable to read file: expected literal', src/main.rs:194:71                                                                                                                                                         
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not sure how much that error can be improved (i.e. if syn returns any relevant details like line numbers). Ideas and PRs welcome.

**Comment by pacak** [comment]
Things syn returns include `Span` somewhere in their structure, `Span` can be used to identify lines: https://docs.rs/proc-macro2/1.0.36/proc_macro2/struct.Span.html

For this specific call you should be able to attach anyhow's context around this line: https://github.com/msrd0/cargo-doc2readme/blob/main/src/input.rs#L221
